version: "3.7"

services:
  flask:
    build:
      context: ./flaskr
      args:
        MODE: production
    restart: always
    ports:
      - 8000:8000
    volumes:
      - flask_static:/var/www/flask/static
    logging:
      options:
        max-size: 1g
volumes:
  flask_static:
