version: '3.7'

services:
  flask:
    build:
      context: ./flaskr
      args:
        MODE: production
    container_name: morse_flask
    volumes:
      - ./flaskr:/code/
    environment:
      MODE: production
      PORT: 8000
      HOST: 0.0.0.0
      LOGS_ROOT: /var/log/morse_code
    env_file:
      - ./envs/redis.env
      - ./envs/flask_prd.env
    ports:
      - 8000:8000
    depends_on:
      - redis
