version: '3.7'

services:
  redis:
    image: "redis:6.2.6-alpine"
    container_name: cesar_test_redis
    env_file:
      - ./envs/redis.env
  flask:
    build: ./flaskr
    container_name: cesar_test_flask
    volumes:
      - ./flaskr:/code/
    environment:
      MODE: development
      PORT: 8000
      HOST: 0.0.0.0
    env_file:
      - ./envs/redis.env
      - ./envs/flask.env
    ports:
      - 8000:8000
    depends_on:
      - redis
